### PR TITLE
Rename prometheus metrics to match units

### LINKED ISSUE #12: Prometheus scrape error: "unit not a suffix of metric"
## Describe the bug

Prometheus seems to require all metrics to end with the unit name.

```
Error: unit not a suffix of metric "containerssh_config_server_failures"
```

## To Reproduce

If you can please provide the steps to reproduce the issue.

1. Run ContainerSSH with metrics enabled 
2. Setup a kubernetes ServiceMonitor to scrape ContainerSSH services

## Expected behavior

ContainerSSH metrics are imported into Prometheus.

## Version

`0.5`

### PR DESCRIPTION
**Pull request by tsipinakis**
## Please describe the change you are making

Fixes #12 

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the MIT-0 license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by janosdebugs** [comment]
Looks good, but will need a documentation change too. Holding this until I figured out what needs changing in the docs.

**Review by janosdebugs — CHANGES_REQUESTED** [review]
@tsipinakis this breaks backwards compatibility. Can you confirm that the previous version doesn't work in Prometheus? Otherwise we'd temporarily need to add new metrics alongside the old ones.

**Comment by tsipinakis** [comment]
I can confirm it doesn't work with Prometheus 2.33.4

```
Error: unit not a suffix of metric "containerssh_config_server_failures"
```

**Review by janosdebugs — APPROVED** [review]
All right then, let's do it!

**Pull request merged**
